services:

  backend:
    build: ./appraisal_dp/appraisal_backend
    container_name: appraisal_backend
    expose:
      - "8000"
    env_file:
      - ./appraisal_dp/appraisal_backend/.env
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: appraisal
      DB_USER: appraisal_user
      DB_PASSWORD: appraisal_pass
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECURE_SSL_REDIRECT: "False"
      DJANGO_SESSION_COOKIE_SECURE: "False"
      DJANGO_CSRF_COOKIE_SECURE: "False"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./appraisal-form
    container_name: appraisal_frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: appraisal_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/defaultt.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    container_name: appraisal_db
    environment:
      POSTGRES_DB: appraisal
      POSTGRES_USER: appraisal_user
      POSTGRES_PASSWORD: appraisal_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appraisal_user -d appraisal"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
